<Project Sdk="Godot.NET.Sdk/4.4.0">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>MonkeSurvivor</RootNamespace>
  </PropertyGroup>
    <ItemGroup>
      <Folder Include="Scripts\Weapons\Magic\" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="Nytraverse.GameFramework.Core" Version="1.0.0" />
      <PackageReference Include="Nytraverse.GameFramework.Godot" Version="1.0.0" />
    </ItemGroup>
</Project>